[package]
name = "ps_one"
version = "0.1.0"
authors = ["kim (grufwub) <grufwub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = ""
termion = ""
dirs = ""
git2 = ""
lazy_static = ""