[package]
name = "ps_one"
version = "0.1.0"
authors = ["kim (grufwub) <grufwub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = "0.10"
termion = "1.5"
dirs = "3.0"
git2 = "0.13"